/*
 * lightgl.js
 * http://github.com/evanw/lightgl.js/
 *
 * Copyright 2011 Evan Wallace
 * Released under the MIT license
 */
var GL=function(){function L(){d.MODELVIEW=F|1;d.PROJECTION=F|2;var b=new h,c=new h;d.modelviewMatrix=new h;d.projectionMatrix=new h;var a=[],e=[],f,l;d.matrixMode=function(b){switch(b){case d.MODELVIEW:f="modelviewMatrix";l=a;break;case d.PROJECTION:f="projectionMatrix";l=e;break;default:throw Error("invalid matrix mode "+b);}};d.loadIdentity=function(){h.identity(d[f])};d.loadMatrix=function(a){a=a.m;for(var b=d[f].m,c=0;16>c;c++)b[c]=a[c]};d.multMatrix=function(a){d.loadMatrix(h.multiply(d[f],
a,c))};d.perspective=function(a,c,e,f){d.multMatrix(h.perspective(a,c,e,f,b))};d.frustum=function(a,c,e,f,l,g){d.multMatrix(h.frustum(a,c,e,f,l,g,b))};d.ortho=function(a,c,e,f,l,g){d.multMatrix(h.ortho(a,c,e,f,l,g,b))};d.scale=function(a,c,e){d.multMatrix(h.scale(a,c,e,b))};d.translate=function(a,c,e){d.multMatrix(h.translate(a,c,e,b))};d.rotate=function(a,c,e,f){d.multMatrix(h.rotate(a,c,e,f,b))};d.lookAt=function(a,c,e,f,l,g,M,q,r){d.multMatrix(h.lookAt(a,c,e,f,l,g,M,q,r,b))};d.pushMatrix=function(){l.push(Array.prototype.slice.call(d[f].m))};
d.popMatrix=function(){var a=l.pop();d[f].m=G?new Float32Array(a):a};d.project=function(a,b,c,e,f,l){e=e||d.modelviewMatrix;f=f||d.projectionMatrix;l=l||d.getParameter(d.VIEWPORT);a=f.transformPoint(e.transformPoint(new g(a,b,c)));return new g(l[0]+l[2]*(0.5*a.x+0.5),l[1]+l[3]*(0.5*a.y+0.5),0.5*a.z+0.5)};d.unProject=function(a,e,f,l,n,u){l=l||d.modelviewMatrix;n=n||d.projectionMatrix;u=u||d.getParameter(d.VIEWPORT);a=new g(2*((a-u[0])/u[2])-1,2*((e-u[1])/u[3])-1,2*f-1);return h.inverse(h.multiply(n,
l,b),c).transformPoint(a)};d.matrixMode(d.MODELVIEW)}function N(){var b=new r({coords:!0,colors:!0,triangles:!1}),c=-1,a=[0,0,0,0],e=[1,1,1,1],f=new C("uniform float pointSize;varying vec4 color;varying vec4 coord;void main(){color=gl_Color;coord=gl_TexCoord;gl_Position=gl_ModelViewProjectionMatrix*gl_Vertex;gl_PointSize=pointSize;}","uniform sampler2D texture;uniform float pointSize;uniform bool useTexture;varying vec4 color;varying vec4 coord;void main(){gl_FragColor=color;if(useTexture)gl_FragColor*=texture2D(texture,coord.xy);}");
d.pointSize=function(a){f.uniforms({pointSize:a})};d.begin=function(a){if(-1!=c)throw Error("mismatched gl.begin() and gl.end() calls");c=a;b.colors=[];b.coords=[];b.vertices=[]};d.color=function(a,b,c,d){e=1==arguments.length?a.toArray().concat(1):[a,b,c,d||1]};d.texCoord=function(b,c){a=1==arguments.length?b.toArray(2):[b,c]};d.vertex=function(c,d,f){b.colors.push(e);b.coords.push(a);b.vertices.push(1==arguments.length?c.toArray():[c,d,f])};d.end=function(){if(-1==c)throw Error("mismatched gl.begin() and gl.end() calls");
b.compile();f.uniforms({useTexture:!!d.getParameter(d.TEXTURE_BINDING_2D)}).draw(b,c);c=-1}}function O(){function b(){for(var a in g)if(h.call(g,a)&&g[a])return!0;return!1}function c(a){var c={},e;for(e in a)c[e]="function"==typeof a[e]?function(b){return function(){b.apply(a,arguments)}}(a[e]):a[e];c.original=a;c.x=c.pageX;c.y=c.pageY;for(e=d.canvas;e;e=e.offsetParent)c.x-=e.offsetLeft,c.y-=e.offsetTop;m?(c.deltaX=c.x-p,c.deltaY=c.y-k):(c.deltaX=0,c.deltaY=0,m=!0);p=c.x;k=c.y;c.dragging=b();c.preventDefault=
function(){c.original.preventDefault()};c.stopPropagation=function(){c.original.stopPropagation()};return c}function a(a){d=l;a=c(a);if(d.onmousemove)d.onmousemove(a);a.preventDefault()}function e(f){d=l;g[f.which]=!1;b()||(document.removeEventListener("mousemove",a),document.removeEventListener("mouseup",e),d.canvas.addEventListener("mousemove",a),d.canvas.addEventListener("mouseup",e));f=c(f);if(d.onmouseup)d.onmouseup(f);f.preventDefault()}function f(){m=!1}var l=d,p=0,k=0,g={},m=!1,h=Object.prototype.hasOwnProperty;
d.canvas.addEventListener("mousedown",function(f){d=l;b()||(document.addEventListener("mousemove",a),document.addEventListener("mouseup",e),d.canvas.removeEventListener("mousemove",a),d.canvas.removeEventListener("mouseup",e));g[f.which]=!0;f=c(f);if(d.onmousedown)d.onmousedown(f);f.preventDefault()});d.canvas.addEventListener("mousemove",a);d.canvas.addEventListener("mouseup",e);d.canvas.addEventListener("mouseover",f);d.canvas.addEventListener("mouseout",f);document.addEventListener("contextmenu",
function(){g={};m=!1})}function H(b){return{8:"BACKSPACE",9:"TAB",13:"ENTER",16:"SHIFT",27:"ESCAPE",32:"SPACE",37:"LEFT",38:"UP",39:"RIGHT",40:"DOWN"}[b]||(65<=b&&90>=b?String.fromCharCode(b):null)}function I(b,c,a){b.addEventListener(c,a)}function P(){(function(b){d.makeCurrent=function(){d=b}})(d);d.animate=function(){function b(){d=e;var f=(new Date).getTime();if(d.onupdate)d.onupdate((f-a)/1E3);if(d.ondraw)d.ondraw();c(b);a=f}var c=window.requestAnimationFrame||window.mozRequestAnimationFrame||
window.webkitRequestAnimationFrame||function(a){setTimeout(a,1E3/60)},a=(new Date).getTime(),e=d;b()};d.fullscreen=function(b){function c(){d.canvas.width=window.innerWidth-e-f;d.canvas.height=window.innerHeight-a-l;d.viewport(0,0,d.canvas.width,d.canvas.height);!b.camera&&"camera"in b||(d.matrixMode(d.PROJECTION),d.loadIdentity(),d.perspective(b.fov||45,d.canvas.width/d.canvas.height,b.near||0.1,b.far||1E3),d.matrixMode(d.MODELVIEW));if(d.ondraw)d.ondraw()}b=b||{};var a=b.paddingTop||0,e=b.paddingLeft||
0,f=b.paddingRight||0,l=b.paddingBottom||0;if(!document.body)throw Error("document.body doesn't exist yet (call gl.fullscreen() from window.onload() or from inside the <body> tag)");document.body.appendChild(d.canvas);document.body.style.overflow="hidden";d.canvas.style.position="absolute";d.canvas.style.left=e+"px";d.canvas.style.top=a+"px";window.addEventListener("resize",c);c()}}function h(){var b=Array.prototype.concat.apply([],arguments);b.length||(b=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);this.m=
G?new Float32Array(b):b}function z(){this.unique=[];this.indices=[];this.map={}}function A(b,c){this.buffer=null;this.target=b;this.type=c;this.data=[]}function r(b){b=b||{};this.vertexBuffers={};this.indexBuffers={};this.addVertexBuffer("vertices","gl_Vertex");b.coords&&this.addVertexBuffer("coords","gl_TexCoord");b.normals&&this.addVertexBuffer("normals","gl_Normal");b.colors&&this.addVertexBuffer("colors","gl_Color");"triangles"in b&&!b.triangles||this.addIndexBuffer("triangles");b.lines&&this.addIndexBuffer("lines")}
function J(b){return new g(2*(b&1)-1,(b&2)-1,(b&4)/2-1)}function w(b,c,a){this.t=arguments.length?b:Number.MAX_VALUE;this.hit=c;this.normal=a}function x(){var b=d.getParameter(d.VIEWPORT),c=d.modelviewMatrix.m,a=new g(c[0],c[4],c[8]),e=new g(c[1],c[5],c[9]),f=new g(c[2],c[6],c[10]),c=new g(c[3],c[7],c[11]);this.eye=new g(-c.dot(a),-c.dot(e),-c.dot(f));a=b[0];e=a+b[2];f=b[1];c=f+b[3];this.ray00=d.unProject(a,f,1).subtract(this.eye);this.ray10=d.unProject(e,f,1).subtract(this.eye);this.ray01=d.unProject(a,
c,1).subtract(this.eye);this.ray11=d.unProject(e,c,1).subtract(this.eye);this.viewport=b}function D(b,c,a){for(;null!=(result=b.exec(c));)a(result)}function C(b,c){function a(a){var b=document.getElementById(a);return b?b.text:a}function e(a,b){var c={},e=/^((\s*\/\/.*\n|\s*#extension.*\n)+)[^]*$/.exec(b);b=e?e[1]+a+b.substr(e[1].length):a+b;D(/\bgl_\w+\b/g,a,function(a){a in c||(b=b.replace(RegExp("\\b"+a+"\\b","g"),B+a),c[a]=!0)});return b}function f(a,b){var c=d.createShader(a);d.shaderSource(c,
b);d.compileShader(c);if(!d.getShaderParameter(c,d.COMPILE_STATUS))throw Error("compile error: "+d.getShaderInfoLog(c));return c}b=a(b);c=a(c);var l=b+c,g={};D(/\b(gl_[^;]*)\b;/g,"uniform mat3 gl_NormalMatrix;uniform mat4 gl_ModelViewMatrix;uniform mat4 gl_ProjectionMatrix;uniform mat4 gl_ModelViewProjectionMatrix;uniform mat4 gl_ModelViewMatrixInverse;uniform mat4 gl_ProjectionMatrixInverse;uniform mat4 gl_ModelViewProjectionMatrixInverse;",function(a){a=a[1];if(-1!=
l.indexOf(a)){var b=a.replace(/[a-z_]/g,"");g[b]=B+a}});-1!=l.indexOf("ftransform")&&(g.MVPM=B+"gl_ModelViewProjectionMatrix");this.usedMatrices=g;b=e("uniform mat3 gl_NormalMatrix;uniform mat4 gl_ModelViewMatrix;uniform mat4 gl_ProjectionMatrix;uniform mat4 gl_ModelViewProjectionMatrix;uniform mat4 gl_ModelViewMatrixInverse;uniform mat4 gl_ProjectionMatrixInverse;uniform mat4 gl_ModelViewProjectionMatrixInverse;attribute vec4 gl_Vertex;attribute vec4 gl_TexCoord;attribute vec3 gl_Normal;attribute vec4 gl_Color;vec4 ftransform(){return gl_ModelViewProjectionMatrix*gl_Vertex;}",
b);c=e("precision highp float;uniform mat3 gl_NormalMatrix;uniform mat4 gl_ModelViewMatrix;uniform mat4 gl_ProjectionMatrix;uniform mat4 gl_ModelViewProjectionMatrix;uniform mat4 gl_ModelViewMatrixInverse;uniform mat4 gl_ProjectionMatrixInverse;uniform mat4 gl_ModelViewProjectionMatrixInverse;",c);this.program=d.createProgram();d.attachShader(this.program,f(d.VERTEX_SHADER,b));d.attachShader(this.program,f(d.FRAGMENT_SHADER,c));d.linkProgram(this.program);if(!d.getProgramParameter(this.program,
d.LINK_STATUS))throw Error("link error: "+d.getProgramInfoLog(this.program));this.attributes={};this.uniformLocations={};var k={};D(/uniform\s+sampler(1D|2D|3D|Cube)\s+(\w+)\s*;/g,b+c,function(a){k[a[2]]=1});this.isSampler=k}function q(b,c,a){a=a||{};this.id=d.createTexture();this.width=b;this.height=c;this.format=a.format||d.RGBA;this.type=a.type||d.UNSIGNED_BYTE;var e=a.filter||a.magFilter||d.LINEAR,f=a.filter||a.minFilter||d.LINEAR;if(this.type===d.FLOAT){if(!q.canUseFloatingPointTextures())throw Error("OES_texture_float is required but not supported");
if((f!==d.NEAREST||e!==d.NEAREST)&&!q.canUseFloatingPointLinearFiltering())throw Error("OES_texture_float_linear is required but not supported");}else if(this.type===d.HALF_FLOAT_OES){if(!q.canUseHalfFloatingPointTextures())throw Error("OES_texture_half_float is required but not supported");if((f!==d.NEAREST||e!==d.NEAREST)&&!q.canUseHalfFloatingPointLinearFiltering())throw Error("OES_texture_half_float_linear is required but not supported");}d.bindTexture(d.TEXTURE_2D,this.id);d.pixelStorei(d.UNPACK_FLIP_Y_WEBGL,
1);d.texParameteri(d.TEXTURE_2D,d.TEXTURE_MAG_FILTER,e);d.texParameteri(d.TEXTURE_2D,d.TEXTURE_MIN_FILTER,f);d.texParameteri(d.TEXTURE_2D,d.TEXTURE_WRAP_S,a.wrap||a.wrapS||d.CLAMP_TO_EDGE);d.texParameteri(d.TEXTURE_2D,d.TEXTURE_WRAP_T,a.wrap||a.wrapT||d.CLAMP_TO_EDGE);d.texImage2D(d.TEXTURE_2D,0,this.format,b,c,0,this.format,this.type,null)}function g(b,c,a){this.x=b||0;this.y=c||0;this.z=a||0}var d,y={create:function(b){b=b||{};var c=document.createElement("canvas");c.width=800;c.height=600;"alpha"in
b||(b.alpha=!1);try{d=c.getContext("webgl",b)}catch(a){}try{d=d||c.getContext("experimental-webgl",b)}catch(e){}if(!d)throw Error("WebGL not supported");d.HALF_FLOAT_OES=36193;L();N();O();P();return d},keys:{},Matrix:h,Indexer:z,Buffer:A,Mesh:r,HitTest:w,Raytracer:x,Shader:C,Texture:q,Vector:g};I(document,"keydown",function(b){if(!b.altKey&&!b.ctrlKey&&!b.metaKey){var c=H(b.keyCode);c&&(y.keys[c]=!0);y.keys[b.keyCode]=!0}});I(document,"keyup",function(b){if(!b.altKey&&!b.ctrlKey&&!b.metaKey){var c=
H(b.keyCode);c&&(y.keys[c]=!1);y.keys[b.keyCode]=!1}});var F=305397760,G="undefined"!=typeof Float32Array;h.prototype={inverse:function(){return h.inverse(this,new h)},transpose:function(){return h.transpose(this,new h)},multiply:function(b){return h.multiply(this,b,new h)},transformPoint:function(b){var c=this.m;return(new g(c[0]*b.x+c[1]*b.y+c[2]*b.z+c[3],c[4]*b.x+c[5]*b.y+c[6]*b.z+c[7],c[8]*b.x+c[9]*b.y+c[10]*b.z+c[11])).divide(c[12]*b.x+c[13]*b.y+c[14]*b.z+c[15])},transformVector:function(b){var c=
this.m;return new g(c[0]*b.x+c[1]*b.y+c[2]*b.z,c[4]*b.x+c[5]*b.y+c[6]*b.z,c[8]*b.x+c[9]*b.y+c[10]*b.z)}};h.inverse=function(b,c){c=c||new h;var a=b.m,e=c.m;e[0]=a[5]*a[10]*a[15]-a[5]*a[14]*a[11]-a[6]*a[9]*a[15]+a[6]*a[13]*a[11]+a[7]*a[9]*a[14]-a[7]*a[13]*a[10];e[1]=-a[1]*a[10]*a[15]+a[1]*a[14]*a[11]+a[2]*a[9]*a[15]-a[2]*a[13]*a[11]-a[3]*a[9]*a[14]+a[3]*a[13]*a[10];e[2]=a[1]*a[6]*a[15]-a[1]*a[14]*a[7]-a[2]*a[5]*a[15]+a[2]*a[13]*a[7]+a[3]*a[5]*a[14]-a[3]*a[13]*a[6];e[3]=-a[1]*a[6]*a[11]+a[1]*a[10]*
a[7]+a[2]*a[5]*a[11]-a[2]*a[9]*a[7]-a[3]*a[5]*a[10]+a[3]*a[9]*a[6];e[4]=-a[4]*a[10]*a[15]+a[4]*a[14]*a[11]+a[6]*a[8]*a[15]-a[6]*a[12]*a[11]-a[7]*a[8]*a[14]+a[7]*a[12]*a[10];e[5]=a[0]*a[10]*a[15]-a[0]*a[14]*a[11]-a[2]*a[8]*a[15]+a[2]*a[12]*a[11]+a[3]*a[8]*a[14]-a[3]*a[12]*a[10];e[6]=-a[0]*a[6]*a[15]+a[0]*a[14]*a[7]+a[2]*a[4]*a[15]-a[2]*a[12]*a[7]-a[3]*a[4]*a[14]+a[3]*a[12]*a[6];e[7]=a[0]*a[6]*a[11]-a[0]*a[10]*a[7]-a[2]*a[4]*a[11]+a[2]*a[8]*a[7]+a[3]*a[4]*a[10]-a[3]*a[8]*a[6];e[8]=a[4]*a[9]*a[15]-a[4]*
a[13]*a[11]-a[5]*a[8]*a[15]+a[5]*a[12]*a[11]+a[7]*a[8]*a[13]-a[7]*a[12]*a[9];e[9]=-a[0]*a[9]*a[15]+a[0]*a[13]*a[11]+a[1]*a[8]*a[15]-a[1]*a[12]*a[11]-a[3]*a[8]*a[13]+a[3]*a[12]*a[9];e[10]=a[0]*a[5]*a[15]-a[0]*a[13]*a[7]-a[1]*a[4]*a[15]+a[1]*a[12]*a[7]+a[3]*a[4]*a[13]-a[3]*a[12]*a[5];e[11]=-a[0]*a[5]*a[11]+a[0]*a[9]*a[7]+a[1]*a[4]*a[11]-a[1]*a[8]*a[7]-a[3]*a[4]*a[9]+a[3]*a[8]*a[5];e[12]=-a[4]*a[9]*a[14]+a[4]*a[13]*a[10]+a[5]*a[8]*a[14]-a[5]*a[12]*a[10]-a[6]*a[8]*a[13]+a[6]*a[12]*a[9];e[13]=a[0]*a[9]*
a[14]-a[0]*a[13]*a[10]-a[1]*a[8]*a[14]+a[1]*a[12]*a[10]+a[2]*a[8]*a[13]-a[2]*a[12]*a[9];e[14]=-a[0]*a[5]*a[14]+a[0]*a[13]*a[6]+a[1]*a[4]*a[14]-a[1]*a[12]*a[6]-a[2]*a[4]*a[13]+a[2]*a[12]*a[5];e[15]=a[0]*a[5]*a[10]-a[0]*a[9]*a[6]-a[1]*a[4]*a[10]+a[1]*a[8]*a[6]+a[2]*a[4]*a[9]-a[2]*a[8]*a[5];for(var a=a[0]*e[0]+a[1]*e[4]+a[2]*e[8]+a[3]*e[12],d=0;16>d;d++)e[d]/=a;return c};h.transpose=function(b,c){c=c||new h;var a=b.m,e=c.m;e[0]=a[0];e[1]=a[4];e[2]=a[8];e[3]=a[12];e[4]=a[1];e[5]=a[5];e[6]=a[9];e[7]=a[13];
e[8]=a[2];e[9]=a[6];e[10]=a[10];e[11]=a[14];e[12]=a[3];e[13]=a[7];e[14]=a[11];e[15]=a[15];return c};h.multiply=function(b,c,a){a=a||new h;b=b.m;c=c.m;var e=a.m;e[0]=b[0]*c[0]+b[1]*c[4]+b[2]*c[8]+b[3]*c[12];e[1]=b[0]*c[1]+b[1]*c[5]+b[2]*c[9]+b[3]*c[13];e[2]=b[0]*c[2]+b[1]*c[6]+b[2]*c[10]+b[3]*c[14];e[3]=b[0]*c[3]+b[1]*c[7]+b[2]*c[11]+b[3]*c[15];e[4]=b[4]*c[0]+b[5]*c[4]+b[6]*c[8]+b[7]*c[12];e[5]=b[4]*c[1]+b[5]*c[5]+b[6]*c[9]+b[7]*c[13];e[6]=b[4]*c[2]+b[5]*c[6]+b[6]*c[10]+b[7]*c[14];e[7]=b[4]*c[3]+b[5]*
c[7]+b[6]*c[11]+b[7]*c[15];e[8]=b[8]*c[0]+b[9]*c[4]+b[10]*c[8]+b[11]*c[12];e[9]=b[8]*c[1]+b[9]*c[5]+b[10]*c[9]+b[11]*c[13];e[10]=b[8]*c[2]+b[9]*c[6]+b[10]*c[10]+b[11]*c[14];e[11]=b[8]*c[3]+b[9]*c[7]+b[10]*c[11]+b[11]*c[15];e[12]=b[12]*c[0]+b[13]*c[4]+b[14]*c[8]+b[15]*c[12];e[13]=b[12]*c[1]+b[13]*c[5]+b[14]*c[9]+b[15]*c[13];e[14]=b[12]*c[2]+b[13]*c[6]+b[14]*c[10]+b[15]*c[14];e[15]=b[12]*c[3]+b[13]*c[7]+b[14]*c[11]+b[15]*c[15];return a};h.identity=function(b){b=b||new h;var c=b.m;c[0]=c[5]=c[10]=c[15]=
1;c[1]=c[2]=c[3]=c[4]=c[6]=c[7]=c[8]=c[9]=c[11]=c[12]=c[13]=c[14]=0;return b};h.perspective=function(b,c,a,e,d){b=Math.tan(b*Math.PI/360)*a;c*=b;return h.frustum(-c,c,-b,b,a,e,d)};h.frustum=function(b,c,a,e,d,l,g){g=g||new h;var k=g.m;k[0]=2*d/(c-b);k[1]=0;k[2]=(c+b)/(c-b);k[3]=0;k[4]=0;k[5]=2*d/(e-a);k[6]=(e+a)/(e-a);k[7]=0;k[8]=0;k[9]=0;k[10]=-(l+d)/(l-d);k[11]=-2*l*d/(l-d);k[12]=0;k[13]=0;k[14]=-1;k[15]=0;return g};h.ortho=function(b,c,a,e,d,l,g){g=g||new h;var k=g.m;k[0]=2/(c-b);k[1]=0;k[2]=0;
k[3]=-(c+b)/(c-b);k[4]=0;k[5]=2/(e-a);k[6]=0;k[7]=-(e+a)/(e-a);k[8]=0;k[9]=0;k[10]=-2/(l-d);k[11]=-(l+d)/(l-d);k[12]=0;k[13]=0;k[14]=0;k[15]=1;return g};h.scale=function(b,c,a,e){e=e||new h;var d=e.m;d[0]=b;d[1]=0;d[2]=0;d[3]=0;d[4]=0;d[5]=c;d[6]=0;d[7]=0;d[8]=0;d[9]=0;d[10]=a;d[11]=0;d[12]=0;d[13]=0;d[14]=0;d[15]=1;return e};h.translate=function(b,c,a,d){d=d||new h;var f=d.m;f[0]=1;f[1]=0;f[2]=0;f[3]=b;f[4]=0;f[5]=1;f[6]=0;f[7]=c;f[8]=0;f[9]=0;f[10]=1;f[11]=a;f[12]=0;f[13]=0;f[14]=0;f[15]=1;return d};
h.rotate=function(b,c,a,d,f){if(!b||!c&&!a&&!d)return h.identity(f);f=f||new h;var l=f.m,g=Math.sqrt(c*c+a*a+d*d);b*=Math.PI/180;c/=g;a/=g;d/=g;g=Math.cos(b);b=Math.sin(b);var k=1-g;l[0]=c*c*k+g;l[1]=c*a*k-d*b;l[2]=c*d*k+a*b;l[3]=0;l[4]=a*c*k+d*b;l[5]=a*a*k+g;l[6]=a*d*k-c*b;l[7]=0;l[8]=d*c*k-a*b;l[9]=d*a*k+c*b;l[10]=d*d*k+g;l[11]=0;l[12]=0;l[13]=0;l[14]=0;l[15]=1;return f};h.lookAt=function(b,c,a,d,f,l,p,k,t,m){m=m||new h;var n=m.m;b=new g(b,c,a);d=new g(d,f,l);k=new g(p,k,t);p=b.subtract(d).unit();
k=k.cross(p).unit();t=p.cross(k).unit();n[0]=k.x;n[1]=k.y;n[2]=k.z;n[3]=-k.dot(b);n[4]=t.x;n[5]=t.y;n[6]=t.z;n[7]=-t.dot(b);n[8]=p.x;n[9]=p.y;n[10]=p.z;n[11]=-p.dot(b);n[12]=0;n[13]=0;n[14]=0;n[15]=1;return m};z.prototype={add:function(b){var c=JSON.stringify(b);c in this.map||(this.map[c]=this.unique.length,this.unique.push(b));return this.map[c]}};A.prototype={compile:function(b){for(var c=[],a=0;a<this.data.length;a+=1E4)c=Array.prototype.concat.apply(c,this.data.slice(a,a+1E4));a=this.data.length?
c.length/this.data.length:0;if(a!=Math.round(a))throw Error("buffer elements not of consistent size, average size is "+a);this.buffer=this.buffer||d.createBuffer();this.buffer.length=c.length;this.buffer.spacing=a;d.bindBuffer(this.target,this.buffer);d.bufferData(this.target,new this.type(c),b||d.STATIC_DRAW)}};r.prototype={addVertexBuffer:function(b,c){(this.vertexBuffers[c]=new A(d.ARRAY_BUFFER,Float32Array)).name=b;this[b]=[]},addIndexBuffer:function(b){this.indexBuffers[b]=new A(d.ELEMENT_ARRAY_BUFFER,
Uint16Array);this[b]=[]},compile:function(){for(var b in this.vertexBuffers){var c=this.vertexBuffers[b];c.data=this[c.name];c.compile()}for(var a in this.indexBuffers)c=this.indexBuffers[a],c.data=this[a],c.compile()},transform:function(b){this.vertices=this.vertices.map(function(a){return b.transformPoint(g.fromArray(a)).toArray()});if(this.normals){var c=b.inverse().transpose();this.normals=this.normals.map(function(a){return c.transformVector(g.fromArray(a)).unit().toArray()})}this.compile();
return this},computeNormals:function(){this.normals||this.addVertexBuffer("normals","gl_Normal");for(var b=0;b<this.vertices.length;b++)this.normals[b]=new g;for(b=0;b<this.triangles.length;b++){var c=this.triangles[b],a=g.fromArray(this.vertices[c[0]]),d=g.fromArray(this.vertices[c[1]]),f=g.fromArray(this.vertices[c[2]]),a=d.subtract(a).cross(f.subtract(a)).unit();this.normals[c[0]]=this.normals[c[0]].add(a);this.normals[c[1]]=this.normals[c[1]].add(a);this.normals[c[2]]=this.normals[c[2]].add(a)}for(b=
0;b<this.vertices.length;b++)this.normals[b]=this.normals[b].unit().toArray();this.compile();return this},computeWireframe:function(){for(var b=new z,c=0;c<this.triangles.length;c++)for(var a=this.triangles[c],d=0;d<a.length;d++){var f=a[d],g=a[(d+1)%a.length];b.add([Math.min(f,g),Math.max(f,g)])}this.lines||this.addIndexBuffer("lines");this.lines=b.unique;this.compile();return this},getAABB:function(){var b={min:new g(Number.MAX_VALUE,Number.MAX_VALUE,Number.MAX_VALUE)};b.max=b.min.negative();for(var c=
0;c<this.vertices.length;c++){var a=g.fromArray(this.vertices[c]);b.min=g.min(b.min,a);b.max=g.max(b.max,a)}return b},getBoundingSphere:function(){for(var b=this.getAABB(),b={center:b.min.add(b.max).divide(2),radius:0},c=0;c<this.vertices.length;c++)b.radius=Math.max(b.radius,g.fromArray(this.vertices[c]).subtract(b.center).length());return b}};r.plane=function(b){b=b||{};var c=new r(b);detailX=b.detailX||b.detail||1;detailY=b.detailY||b.detail||1;for(b=0;b<=detailY;b++)for(var a=b/detailY,d=0;d<=
detailX;d++){var f=d/detailX;c.vertices.push([2*f-1,2*a-1,0]);c.coords&&c.coords.push([f,a]);c.normals&&c.normals.push([0,0,1]);d<detailX&&b<detailY&&(f=d+b*(detailX+1),c.triangles.push([f,f+1,f+detailX+1]),c.triangles.push([f+detailX+1,f+1,f+detailX+2]))}c.compile();return c};var K=[[0,4,2,6,-1,0,0],[1,3,5,7,1,0,0],[0,1,4,5,0,-1,0],[2,6,3,7,0,1,0],[0,2,1,3,0,0,-1],[4,5,6,7,0,0,1]];r.cube=function(b){b=new r(b);for(var c=0;c<K.length;c++){for(var a=K[c],d=4*c,f=0;4>f;f++)b.vertices.push(J(a[f]).toArray()),
b.coords&&b.coords.push([f&1,(f&2)/2]),b.normals&&b.normals.push(a.slice(4,7));b.triangles.push([d,d+1,d+2]);b.triangles.push([d+2,d+1,d+3])}b.compile();return b};r.sphere=function(b){b=b||{};var c=new r(b),a=new z;detail=b.detail||6;for(b=0;8>b;b++)for(var d=J(b),f=0<d.x*d.y*d.z,l=[],p=0;p<=detail;p++){for(var k=0;p+k<=detail;k++){var h=p/detail,m=k/detail,n=(detail-p-k)/detail,m={vertex:(new g(h+(h-h*h)/2,m+(m-m*m)/2,n+(n-n*n)/2)).unit().multiply(d).toArray()};c.coords&&(m.coord=0<d.y?[1-h,n]:[n,
1-h]);l.push(a.add(m))}if(0<p)for(k=0;p+k<=detail;k++)h=(p-1)*(detail+1)+(p-1-(p-1)*(p-1))/2+k,m=p*(detail+1)+(p-p*p)/2+k,c.triangles.push(f?[l[h],l[m],l[h+1]]:[l[h],l[h+1],l[m]]),p+k<detail&&c.triangles.push(f?[l[m],l[m+1],l[h+1]]:[l[m],l[h+1],l[m+1]])}c.vertices=a.unique.map(function(a){return a.vertex});c.coords&&(c.coords=a.unique.map(function(a){return a.coord}));c.normals&&(c.normals=c.vertices);c.compile();return c};r.load=function(b,c){c=c||{};"coords"in c||(c.coords=!!b.coords);"normals"in
c||(c.normals=!!b.normals);"colors"in c||(c.colors=!!b.colors);"triangles"in c||(c.triangles=!!b.triangles);"lines"in c||(c.lines=!!b.lines);var a=new r(c);a.vertices=b.vertices;a.coords&&(a.coords=b.coords);a.normals&&(a.normals=b.normals);a.colors&&(a.colors=b.colors);a.triangles&&(a.triangles=b.triangles);a.lines&&(a.lines=b.lines);a.compile();return a};w.prototype={mergeWith:function(b){0<b.t&&b.t<this.t&&(this.t=b.t,this.hit=b.hit,this.normal=b.normal)}};x.prototype={getRayForPixel:function(b,
c){b=(b-this.viewport[0])/this.viewport[2];c=1-(c-this.viewport[1])/this.viewport[3];var a=g.lerp(this.ray00,this.ray10,b),d=g.lerp(this.ray01,this.ray11,b);return g.lerp(a,d,c).unit()}};x.hitTestBox=function(b,c,a,d){var f=a.subtract(b).divide(c),l=d.subtract(b).divide(c),h=g.min(f,l),f=g.max(f,l),h=h.max(),f=f.min();return 0<h&&h<f?(b=b.add(c.multiply(h)),a=a.add(1E-6),d=d.subtract(1E-6),new w(h,b,new g((b.x>d.x)-(b.x<a.x),(b.y>d.y)-(b.y<a.y),(b.z>d.z)-(b.z<a.z)))):null};x.hitTestSphere=function(b,
c,a,d){var f=b.subtract(a),g=c.dot(c),h=2*c.dot(f),f=f.dot(f)-d*d,f=h*h-4*g*f;return 0<f?(g=(-h-Math.sqrt(f))/(2*g),b=b.add(c.multiply(g)),new w(g,b,b.subtract(a).divide(d))):null};x.hitTestTriangle=function(b,c,a,d,f){var g=d.subtract(a),h=f.subtract(a);f=g.cross(h).unit();d=f.dot(a.subtract(b))/f.dot(c);if(0<d){b=b.add(c.multiply(d));var k=b.subtract(a);a=h.dot(h);c=h.dot(g);var h=h.dot(k),q=g.dot(g),g=g.dot(k),k=a*q-c*c,q=(q*h-c*g)/k,g=(a*g-c*h)/k;if(0<=q&&0<=g&&1>=q+g)return new w(d,b,f)}return null};
var B="LIGHTGL";new h;new h;C.prototype={uniforms:function(b){d.useProgram(this.program);for(var c in b){var a=this.uniformLocations[c]||d.getUniformLocation(this.program,c);if(a){this.uniformLocations[c]=a;var e=b[c];e instanceof g?e=[e.x,e.y,e.z]:e instanceof h&&(e=e.m);var f=Object.prototype.toString.call(e);if("[object Array]"==f||"[object Float32Array]"==f)switch(e.length){case 1:d.uniform1fv(a,new Float32Array(e));break;case 2:d.uniform2fv(a,new Float32Array(e));break;case 3:d.uniform3fv(a,
new Float32Array(e));break;case 4:d.uniform4fv(a,new Float32Array(e));break;case 9:d.uniformMatrix3fv(a,!1,new Float32Array([e[0],e[3],e[6],e[1],e[4],e[7],e[2],e[5],e[8]]));break;case 16:d.uniformMatrix4fv(a,!1,new Float32Array([e[0],e[4],e[8],e[12],e[1],e[5],e[9],e[13],e[2],e[6],e[10],e[14],e[3],e[7],e[11],e[15]]));break;default:throw Error("don't know how to load uniform \""+c+'" of length '+e.length);}else if(f=Object.prototype.toString.call(e),"[object Number]"==f||"[object Boolean]"==f)(this.isSampler[c]?
d.uniform1i:d.uniform1f).call(d,a,e);else throw Error('attempted to set uniform "'+c+'" to invalid value '+e);}}return this},draw:function(b,c){this.drawBuffers(b.vertexBuffers,b.indexBuffers[c==d.LINES?"lines":"triangles"],2>arguments.length?d.TRIANGLES:c)},drawBuffers:function(b,c,a){var e=this.usedMatrices,f=d.modelviewMatrix,g=d.projectionMatrix,h=e.MVMI||e.NM?f.inverse():null,k=e.PMI?g.inverse():null,q=e.MVPM||e.MVPMI?g.multiply(f):null,m={};e.MVM&&(m[e.MVM]=f);e.MVMI&&(m[e.MVMI]=h);e.PM&&(m[e.PM]=
g);e.PMI&&(m[e.PMI]=k);e.MVPM&&(m[e.MVPM]=q);e.MVPMI&&(m[e.MVPMI]=q.inverse());e.NM&&(f=h.m,m[e.NM]=[f[0],f[4],f[8],f[1],f[5],f[9],f[2],f[6],f[10]]);this.uniforms(m);var e=0,n;for(n in b)m=b[n],f=this.attributes[n]||d.getAttribLocation(this.program,n.replace(/^(gl_.*)$/,B+"$1")),-1!=f&&m.buffer&&(this.attributes[n]=f,d.bindBuffer(d.ARRAY_BUFFER,m.buffer),d.enableVertexAttribArray(f),d.vertexAttribPointer(f,m.buffer.spacing,d.FLOAT,!1,0,0),e=m.buffer.length/m.buffer.spacing);for(n in this.attributes)n in
b||d.disableVertexAttribArray(this.attributes[n]);!e||c&&!c.buffer||(c?(d.bindBuffer(d.ELEMENT_ARRAY_BUFFER,c.buffer),d.drawElements(a,c.buffer.length,d.UNSIGNED_SHORT,0)):d.drawArrays(a,0,e));return this}};var v,s,E;q.prototype={bind:function(b){d.activeTexture(d.TEXTURE0+(b||0));d.bindTexture(d.TEXTURE_2D,this.id)},unbind:function(b){d.activeTexture(d.TEXTURE0+(b||0));d.bindTexture(d.TEXTURE_2D,null)},canDrawTo:function(){v=v||d.createFramebuffer();d.bindFramebuffer(d.FRAMEBUFFER,v);d.framebufferTexture2D(d.FRAMEBUFFER,
d.COLOR_ATTACHMENT0,d.TEXTURE_2D,this.id,0);var b=d.checkFramebufferStatus(d.FRAMEBUFFER)==d.FRAMEBUFFER_COMPLETE;d.bindFramebuffer(d.FRAMEBUFFER,null);return b},drawTo:function(b){var c=d.getParameter(d.VIEWPORT);v=v||d.createFramebuffer();s=s||d.createRenderbuffer();d.bindFramebuffer(d.FRAMEBUFFER,v);d.bindRenderbuffer(d.RENDERBUFFER,s);if(this.width!=s.width||this.height!=s.height)s.width=this.width,s.height=this.height,d.renderbufferStorage(d.RENDERBUFFER,d.DEPTH_COMPONENT16,this.width,this.height);
d.framebufferTexture2D(d.FRAMEBUFFER,d.COLOR_ATTACHMENT0,d.TEXTURE_2D,this.id,0);d.framebufferRenderbuffer(d.FRAMEBUFFER,d.DEPTH_ATTACHMENT,d.RENDERBUFFER,s);if(d.checkFramebufferStatus(d.FRAMEBUFFER)!=d.FRAMEBUFFER_COMPLETE)throw Error("Rendering to this texture is not supported (incomplete framebuffer)");d.viewport(0,0,this.width,this.height);b();d.bindFramebuffer(d.FRAMEBUFFER,null);d.bindRenderbuffer(d.RENDERBUFFER,null);d.viewport(c[0],c[1],c[2],c[3])},swapWith:function(b){var c;c=b.id;b.id=
this.id;this.id=c;c=b.width;b.width=this.width;this.width=c;c=b.height;b.height=this.height;this.height=c}};q.fromImage=function(b,c){c=c||{};var a=new q(b.width,b.height,c);try{d.texImage2D(d.TEXTURE_2D,0,a.format,a.format,a.type,b)}catch(e){if("file:"==location.protocol)throw Error('image not loaded for security reasons (serve this page over "http://" instead)');throw Error("image not loaded for security reasons (image must originate from the same domain as this page or use Cross-Origin Resource Sharing)");
}c.minFilter&&(c.minFilter!=d.NEAREST&&c.minFilter!=d.LINEAR)&&d.generateMipmap(d.TEXTURE_2D);return a};q.fromURL=function(b,c){E=E||function(){var a=document.createElement("canvas").getContext("2d");a.canvas.width=a.canvas.height=128;for(var b=0;b<a.canvas.height;b+=16)for(var c=0;c<a.canvas.width;c+=16)a.fillStyle=(c^b)&16?"#FFF":"#DDD",a.fillRect(c,b,16,16);return a.canvas}();var a=q.fromImage(E,c),e=new Image,f=d;e.onload=function(){f.makeCurrent();q.fromImage(e,c).swapWith(a)};e.src=b;return a};
q.canUseFloatingPointTextures=function(){return!!d.getExtension("OES_texture_float")};q.canUseFloatingPointLinearFiltering=function(){return!!d.getExtension("OES_texture_float_linear")};q.canUseHalfFloatingPointTextures=function(){return!!d.getExtension("OES_texture_half_float")};q.canUseHalfFloatingPointLinearFiltering=function(){return!!d.getExtension("OES_texture_half_float_linear")};g.prototype={negative:function(){return new g(-this.x,-this.y,-this.z)},add:function(b){return b instanceof g?new g(this.x+
b.x,this.y+b.y,this.z+b.z):new g(this.x+b,this.y+b,this.z+b)},subtract:function(b){return b instanceof g?new g(this.x-b.x,this.y-b.y,this.z-b.z):new g(this.x-b,this.y-b,this.z-b)},multiply:function(b){return b instanceof g?new g(this.x*b.x,this.y*b.y,this.z*b.z):new g(this.x*b,this.y*b,this.z*b)},divide:function(b){return b instanceof g?new g(this.x/b.x,this.y/b.y,this.z/b.z):new g(this.x/b,this.y/b,this.z/b)},equals:function(b){return this.x==b.x&&this.y==b.y&&this.z==b.z},dot:function(b){return this.x*
b.x+this.y*b.y+this.z*b.z},cross:function(b){return new g(this.y*b.z-this.z*b.y,this.z*b.x-this.x*b.z,this.x*b.y-this.y*b.x)},length:function(){return Math.sqrt(this.dot(this))},unit:function(){return this.divide(this.length())},min:function(){return Math.min(Math.min(this.x,this.y),this.z)},max:function(){return Math.max(Math.max(this.x,this.y),this.z)},toAngles:function(){return{theta:Math.atan2(this.z,this.x),phi:Math.asin(this.y/this.length())}},angleTo:function(b){return Math.acos(this.dot(b)/
(this.length()*b.length()))},toArray:function(b){return[this.x,this.y,this.z].slice(0,b||3)},clone:function(){return new g(this.x,this.y,this.z)},init:function(b,c,a){this.x=b;this.y=c;this.z=a;return this}};g.negative=function(b,c){c.x=-b.x;c.y=-b.y;c.z=-b.z;return c};g.add=function(b,c,a){c instanceof g?(a.x=b.x+c.x,a.y=b.y+c.y,a.z=b.z+c.z):(a.x=b.x+c,a.y=b.y+c,a.z=b.z+c);return a};g.subtract=function(b,c,a){c instanceof g?(a.x=b.x-c.x,a.y=b.y-c.y,a.z=b.z-c.z):(a.x=b.x-c,a.y=b.y-c,a.z=b.z-c);return a};
g.multiply=function(b,c,a){c instanceof g?(a.x=b.x*c.x,a.y=b.y*c.y,a.z=b.z*c.z):(a.x=b.x*c,a.y=b.y*c,a.z=b.z*c);return a};g.divide=function(b,c,a){c instanceof g?(a.x=b.x/c.x,a.y=b.y/c.y,a.z=b.z/c.z):(a.x=b.x/c,a.y=b.y/c,a.z=b.z/c);return a};g.cross=function(b,c,a){a.x=b.y*c.z-b.z*c.y;a.y=b.z*c.x-b.x*c.z;a.z=b.x*c.y-b.y*c.x;return a};g.unit=function(b,c){var a=b.length();c.x=b.x/a;c.y=b.y/a;c.z=b.z/a;return c};g.fromAngles=function(b,c){return new g(Math.cos(b)*Math.cos(c),Math.sin(c),Math.sin(b)*
Math.cos(c))};g.randomDirection=function(){return g.fromAngles(2*Math.random()*Math.PI,Math.asin(2*Math.random()-1))};g.min=function(b,c){return new g(Math.min(b.x,c.x),Math.min(b.y,c.y),Math.min(b.z,c.z))};g.max=function(b,c){return new g(Math.max(b.x,c.x),Math.max(b.y,c.y),Math.max(b.z,c.z))};g.lerp=function(b,c,a){return c.subtract(b).multiply(a).add(b)};g.fromArray=function(b){return new g(b[0],b[1],b[2])};g.angleBetween=function(b,c){return b.angleTo(c)};return y}();
