/*
 * lightgl.js
 * http://github.com/evanw/lightgl.js/
 *
 * Copyright 2011 Evan Wallace
 * Released under the MIT license
 */
var GL=function(){function H(){e.MODELVIEW=B|1;e.PROJECTION=B|2;var b=new l,c=new l;e.modelviewMatrix=new l;e.projectionMatrix=new l;var a=[],d=[],f,i;e.matrixMode=function(g){switch(g){case e.MODELVIEW:f="modelviewMatrix";i=a;break;case e.PROJECTION:f="projectionMatrix";i=d;break;default:throw"invalid matrix mode "+g;}};e.loadIdentity=function(){l.identity(e[f])};e.loadMatrix=function(g){g=g.m;for(var h=e[f].m,k=0;k<16;k++)h[k]=g[k]};e.multMatrix=function(g){e.loadMatrix(l.multiply(e[f],g,c))};e.perspective=
function(g,h,k,m){e.multMatrix(l.perspective(g,h,k,m,b))};e.frustum=function(g,h,k,m,n,o){e.multMatrix(l.frustum(g,h,k,m,n,o,b))};e.ortho=function(g,h,k,m,n,o){e.multMatrix(l.ortho(g,h,k,m,n,o,b))};e.scale=function(g,h,k){e.multMatrix(l.scale(g,h,k,b))};e.translate=function(g,h,k){e.multMatrix(l.translate(g,h,k,b))};e.rotate=function(g,h,k,m){e.multMatrix(l.rotate(g,h,k,m,b))};e.lookAt=function(g,h,k,m,n,o,I,J,K){e.multMatrix(l.lookAt(g,h,k,m,n,o,I,J,K,b))};e.pushMatrix=function(){i.push(Array.prototype.slice.call(e[f].m))};
e.popMatrix=function(){var g=i.pop();e[f].m=C?new Float32Array(g):g};e.project=function(g,h,k,m,n,o){m=m||e.modelviewMatrix;n=n||e.projectionMatrix;o=o||e.getParameter(e.VIEWPORT);g=n.transformPoint(m.transformPoint(new j(g,h,k)));return new j(o[0]+o[2]*(g.x*0.5+0.5),o[1]+o[3]*(g.y*0.5+0.5),g.z*0.5+0.5)};e.unProject=function(g,h,k,m,n,o){m=m||e.modelviewMatrix;n=n||e.projectionMatrix;o=o||e.getParameter(e.VIEWPORT);g=new j((g-o[0])/o[2]*2-1,(h-o[1])/o[3]*2-1,k*2-1);return l.inverse(l.multiply(n,m,
b),c).transformPoint(g)};e.matrixMode(e.MODELVIEW)}function L(){var b={mesh:new p({coords:true,colors:true,triangles:false}),mode:-1,coord:[0,0,0,0],color:[1,1,1,1],pointSize:1,shader:new y("uniform float pointSize;varying vec4 color;varying vec4 coord;varying vec2 pixel;void main(){color=gl_Color;coord=gl_TexCoord;gl_Position=gl_ModelViewProjectionMatrix*gl_Vertex;pixel=gl_Position.xy/gl_Position.w*0.5+0.5;gl_PointSize=pointSize;}",
"uniform sampler2D texture;uniform float pointSize;uniform bool useTexture;uniform vec2 windowSize;varying vec4 color;varying vec4 coord;varying vec2 pixel;void main(){gl_FragColor=color;if(useTexture)gl_FragColor*=texture2D(texture,coord.xy);}")};e.pointSize=function(c){b.shader.uniforms({pointSize:c})};e.begin=function(c){if(b.mode!=-1)throw"mismatched gl.begin() and gl.end() calls";b.mode=c;b.mesh.colors=[];b.mesh.coords=
[];b.mesh.vertices=[]};e.color=function(c,a,d,f){b.color=arguments.length==1?c.toArray().concat(1):[c,a,d,f||1]};e.texCoord=function(c,a){b.coord=arguments.length==1?c.toArray(2):[c,a]};e.vertex=function(c,a,d){b.mesh.colors.push(b.color);b.mesh.coords.push(b.coord);b.mesh.vertices.push(arguments.length==1?c.toArray():[c,a,d])};e.end=function(){if(b.mode==-1)throw"mismatched gl.begin() and gl.end() calls";b.mesh.compile();b.shader.uniforms({windowSize:[e.canvas.width,e.canvas.height],useTexture:!!e.getParameter(e.TEXTURE_BINDING_2D)}).draw(b.mesh,
b.mode);b.mode=-1}}function M(){function b(f){for(var i=f.pageX,g=f.pageY,h=e.canvas;h;h=h.offsetParent){i-=h.offsetLeft;g-=h.offsetTop}f.deltaX=i-c;f.deltaY=g-a;f.x=i;f.y=g;c=i;a=g;f.dragging=false;for(var k in d)if(d[k])f.dragging=true}var c=0,a=0,d={};s(e.canvas,"mousedown",function(f){d[f.which]=true;b(f);e.onmousedown&&e.onmousedown(f)});s(e.canvas,"mousemove",function(f){b(f);e.onmousemove&&e.onmousemove(f)});s(e.canvas,"mouseup",function(f){d[f.which]=false;b(f);e.onmouseup&&e.onmouseup(f)})}
function D(b){return{8:"BACKSPACE",9:"TAB",13:"ENTER",16:"SHIFT",27:"ESCAPE",32:"SPACE",37:"LEFT",38:"UP",39:"RIGHT",40:"DOWN"}[b]||(b>=65&&b<=90?String.fromCharCode(b):null)}function s(b,c,a){b.addEventListener(c,a)}function N(){(function(b){e.makeCurrent=function(){e=b}})(e);e.animate=function(){function b(){e=d;var f=new Date;e.onupdate&&e.onupdate((f-a)/1E3);e.ondraw&&e.ondraw();c(b);a=f}var c=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||function(f){setTimeout(f,
1E3/60)},a=new Date,d=e;b()};e.fullscreen=function(b){function c(){e.canvas.width=window.innerWidth-d-f;e.canvas.height=window.innerHeight-a-i;e.viewport(0,0,e.canvas.width,e.canvas.height);if(b.camera||!("camera"in b)){e.matrixMode(e.PROJECTION);e.loadIdentity();e.perspective(b.fov||45,e.canvas.width/e.canvas.height,b.near||0.1,b.far||1E3);e.matrixMode(e.MODELVIEW)}e.ondraw&&e.ondraw()}b=b||{};var a=b.paddingTop||0,d=b.paddingLeft||0,f=b.paddingRight||0,i=b.paddingBottom||0;if(!document.body)throw"document.body doesn't exist yet (call gl.fullscreen() from window.onload() or from inside the <body> tag)";
document.body.appendChild(e.canvas);document.body.style.overflow="hidden";e.canvas.style.position="absolute";e.canvas.style.left=d+"px";e.canvas.style.top=a+"px";window.addEventListener("resize",c);c()}}function l(){var b=Array.prototype.concat.apply([],arguments);b.length||(b=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);this.m=C?new Float32Array(b):b}function w(){this.unique=[];this.indices=[];this.map={}}function x(b,c){this.buffer=null;this.target=b;this.type=c;this.data=[]}function p(b){b=b||{};this.vertexBuffers=
{};this.indexBuffers={};this.addVertexBuffer("vertices","gl_Vertex");b.coords&&this.addVertexBuffer("coords","gl_TexCoord");b.normals&&this.addVertexBuffer("normals","gl_Normal");b.colors&&this.addVertexBuffer("colors","gl_Color");if(!("triangles"in b)||b.triangles)this.addIndexBuffer("triangles");b.lines&&this.addIndexBuffer("lines")}function E(b){return new j((b&1)*2-1,(b&2)-1,(b&4)/2-1)}function t(b,c,a){this.t=arguments.length?b:Number.MAX_VALUE;this.hit=c;this.normal=a}function u(){var b=e.getParameter(e.VIEWPORT),
c=e.modelviewMatrix.m,a=new j(c[0],c[4],c[8]),d=new j(c[1],c[5],c[9]),f=new j(c[2],c[6],c[10]);c=new j(c[3],c[7],c[11]);this.eye=new j(-c.dot(a),-c.dot(d),-c.dot(f));a=b[0];d=a+b[2];f=b[1];c=f+b[3];this.ray00=e.unProject(a,f,1).subtract(this.eye);this.ray10=e.unProject(d,f,1).subtract(this.eye);this.ray01=e.unProject(a,c,1).subtract(this.eye);this.ray11=e.unProject(d,c,1).subtract(this.eye);this.viewport=b}function y(b,c){function a(h,k,m){for(;(result=h.exec(k))!=null;)m(result)}function d(h,k){var m=
{},n=/^((\s*\/\/.*\n|\s*#extension.*\n)+)[^]*$/.exec(k);k=n?n[1]+h+k.substr(n[1].length):h+k;a(/\bgl_\w+\b/g,h,function(o){if(!(o in m)){k=k.replace(RegExp("\\b"+o+"\\b","g"),"_"+o);m[o]=true}});return k}function f(h,k){var m=e.createShader(h);e.shaderSource(m,k);e.compileShader(m);if(!e.getShaderParameter(m,e.COMPILE_STATUS))throw"compile error: "+e.getShaderInfoLog(m);return m}var i=b+c;this.needsMVPM=/(gl_ModelViewProjectionMatrix|ftransform)/.test(i);this.needsNM=/gl_NormalMatrix/.test(i);b=d("attribute vec4 gl_Vertex;attribute vec4 gl_TexCoord;attribute vec3 gl_Normal;attribute vec4 gl_Color;uniform mat3 gl_NormalMatrix;uniform mat4 gl_ModelViewMatrix;uniform mat4 gl_ProjectionMatrix;uniform mat4 gl_ModelViewProjectionMatrix;vec4 ftransform(){return gl_ModelViewProjectionMatrix*gl_Vertex;}",
b);c=d("precision highp float;uniform mat3 gl_NormalMatrix;uniform mat4 gl_ModelViewMatrix;uniform mat4 gl_ProjectionMatrix;uniform mat4 gl_ModelViewProjectionMatrix;",c);this.program=e.createProgram();e.attachShader(this.program,f(e.VERTEX_SHADER,b));e.attachShader(this.program,f(e.FRAGMENT_SHADER,c));e.linkProgram(this.program);if(!e.getProgramParameter(this.program,e.LINK_STATUS))throw"link error: "+e.getProgramInfoLog(this.program);this.attributes={};var g={};a(/uniform\s+sampler(1D|2D|3D|Cube)\s+(\w+)\s*;/g,
b+c,function(h){g[h[2]]=1});this.isSampler=g}function r(b,c,a){a=a||{};this.id=e.createTexture();this.width=b;this.height=c;this.format=a.format||e.RGBA;this.type=a.type||e.UNSIGNED_BYTE;e.bindTexture(e.TEXTURE_2D,this.id);e.pixelStorei(e.UNPACK_FLIP_Y_WEBGL,1);e.texParameteri(e.TEXTURE_2D,e.TEXTURE_MAG_FILTER,a.filter||a.magFilter||e.LINEAR);e.texParameteri(e.TEXTURE_2D,e.TEXTURE_MIN_FILTER,a.filter||a.minFilter||e.LINEAR);e.texParameteri(e.TEXTURE_2D,e.TEXTURE_WRAP_S,a.wrap||a.wrapS||e.CLAMP_TO_EDGE);
e.texParameteri(e.TEXTURE_2D,e.TEXTURE_WRAP_T,a.wrap||a.wrapT||e.CLAMP_TO_EDGE);e.texImage2D(e.TEXTURE_2D,0,this.format,b,c,0,this.format,this.type,null)}function j(b,c,a){this.x=b||0;this.y=c||0;this.z=a||0}var e,v={create:function(b){b=b||{};var c=document.createElement("canvas");c.width=800;c.height=600;if(!("alpha"in b))b.alpha=false;try{e=c.getContext("webgl",b)}catch(a){}try{e=e||c.getContext("experimental-webgl",b)}catch(d){}if(!e)throw"WebGL not supported";H();L();M();N();return e},keys:{},
Matrix:l,Indexer:w,Buffer:x,Mesh:p,HitTest:t,Raytracer:u,Shader:y,Texture:r,Vector:j};s(document,"keydown",function(b){if(!b.altKey&&!b.ctrlKey&&!b.metaKey){var c=D(b.keyCode);if(c)v.keys[c]=true;v.keys[b.keyCode]=true}});s(document,"keyup",function(b){if(!b.altKey&&!b.ctrlKey&&!b.metaKey){var c=D(b.keyCode);if(c)v.keys[c]=false;v.keys[b.keyCode]=false}});var B=305397760,C=typeof Float32Array!="undefined";l.prototype={inverse:function(){return l.inverse(this,new l)},transpose:function(){return l.transpose(this,
new l)},multiply:function(b){return l.multiply(this,b,new l)},transformPoint:function(b){var c=this.m;return(new j(c[0]*b.x+c[1]*b.y+c[2]*b.z+c[3],c[4]*b.x+c[5]*b.y+c[6]*b.z+c[7],c[8]*b.x+c[9]*b.y+c[10]*b.z+c[11])).divide(c[12]*b.x+c[13]*b.y+c[14]*b.z+c[15])},transformVector:function(b){var c=this.m;return new j(c[0]*b.x+c[1]*b.y+c[2]*b.z,c[4]*b.x+c[5]*b.y+c[6]*b.z,c[8]*b.x+c[9]*b.y+c[10]*b.z)}};l.inverse=function(b,c){c=c||new l;var a=b.m,d=c.m;d[0]=a[5]*a[10]*a[15]-a[5]*a[14]*a[11]-a[6]*a[9]*a[15]+
a[6]*a[13]*a[11]+a[7]*a[9]*a[14]-a[7]*a[13]*a[10];d[1]=-a[1]*a[10]*a[15]+a[1]*a[14]*a[11]+a[2]*a[9]*a[15]-a[2]*a[13]*a[11]-a[3]*a[9]*a[14]+a[3]*a[13]*a[10];d[2]=a[1]*a[6]*a[15]-a[1]*a[14]*a[7]-a[2]*a[5]*a[15]+a[2]*a[13]*a[7]+a[3]*a[5]*a[14]-a[3]*a[13]*a[6];d[3]=-a[1]*a[6]*a[11]+a[1]*a[10]*a[7]+a[2]*a[5]*a[11]-a[2]*a[9]*a[7]-a[3]*a[5]*a[10]+a[3]*a[9]*a[6];d[4]=-a[4]*a[10]*a[15]+a[4]*a[14]*a[11]+a[6]*a[8]*a[15]-a[6]*a[12]*a[11]-a[7]*a[8]*a[14]+a[7]*a[12]*a[10];d[5]=a[0]*a[10]*a[15]-a[0]*a[14]*a[11]-
a[2]*a[8]*a[15]+a[2]*a[12]*a[11]+a[3]*a[8]*a[14]-a[3]*a[12]*a[10];d[6]=-a[0]*a[6]*a[15]+a[0]*a[14]*a[7]+a[2]*a[4]*a[15]-a[2]*a[12]*a[7]-a[3]*a[4]*a[14]+a[3]*a[12]*a[6];d[7]=a[0]*a[6]*a[11]-a[0]*a[10]*a[7]-a[2]*a[4]*a[11]+a[2]*a[8]*a[7]+a[3]*a[4]*a[10]-a[3]*a[8]*a[6];d[8]=a[4]*a[9]*a[15]-a[4]*a[13]*a[11]-a[5]*a[8]*a[15]+a[5]*a[12]*a[11]+a[7]*a[8]*a[13]-a[7]*a[12]*a[9];d[9]=-a[0]*a[9]*a[15]+a[0]*a[13]*a[11]+a[1]*a[8]*a[15]-a[1]*a[12]*a[11]-a[3]*a[8]*a[13]+a[3]*a[12]*a[9];d[10]=a[0]*a[5]*a[15]-a[0]*
a[13]*a[7]-a[1]*a[4]*a[15]+a[1]*a[12]*a[7]+a[3]*a[4]*a[13]-a[3]*a[12]*a[5];d[11]=-a[0]*a[5]*a[11]+a[0]*a[9]*a[7]+a[1]*a[4]*a[11]-a[1]*a[8]*a[7]-a[3]*a[4]*a[9]+a[3]*a[8]*a[5];d[12]=-a[4]*a[9]*a[14]+a[4]*a[13]*a[10]+a[5]*a[8]*a[14]-a[5]*a[12]*a[10]-a[6]*a[8]*a[13]+a[6]*a[12]*a[9];d[13]=a[0]*a[9]*a[14]-a[0]*a[13]*a[10]-a[1]*a[8]*a[14]+a[1]*a[12]*a[10]+a[2]*a[8]*a[13]-a[2]*a[12]*a[9];d[14]=-a[0]*a[5]*a[14]+a[0]*a[13]*a[6]+a[1]*a[4]*a[14]-a[1]*a[12]*a[6]-a[2]*a[4]*a[13]+a[2]*a[12]*a[5];d[15]=a[0]*a[5]*
a[10]-a[0]*a[9]*a[6]-a[1]*a[4]*a[10]+a[1]*a[8]*a[6]+a[2]*a[4]*a[9]-a[2]*a[8]*a[5];a=a[0]*d[0]+a[1]*d[4]+a[2]*d[8]+a[3]*d[12];for(var f=0;f<16;f++)d[f]/=a;return c};l.transpose=function(b,c){c=c||new l;var a=b.m,d=c.m;d[0]=a[0];d[1]=a[4];d[2]=a[8];d[3]=a[12];d[4]=a[1];d[5]=a[5];d[6]=a[9];d[7]=a[13];d[8]=a[2];d[9]=a[6];d[10]=a[10];d[11]=a[14];d[12]=a[3];d[13]=a[7];d[14]=a[11];d[15]=a[15];return c};l.multiply=function(b,c,a){a=a||new l;b=b.m;c=c.m;var d=a.m;d[0]=b[0]*c[0]+b[1]*c[4]+b[2]*c[8]+b[3]*c[12];
d[1]=b[0]*c[1]+b[1]*c[5]+b[2]*c[9]+b[3]*c[13];d[2]=b[0]*c[2]+b[1]*c[6]+b[2]*c[10]+b[3]*c[14];d[3]=b[0]*c[3]+b[1]*c[7]+b[2]*c[11]+b[3]*c[15];d[4]=b[4]*c[0]+b[5]*c[4]+b[6]*c[8]+b[7]*c[12];d[5]=b[4]*c[1]+b[5]*c[5]+b[6]*c[9]+b[7]*c[13];d[6]=b[4]*c[2]+b[5]*c[6]+b[6]*c[10]+b[7]*c[14];d[7]=b[4]*c[3]+b[5]*c[7]+b[6]*c[11]+b[7]*c[15];d[8]=b[8]*c[0]+b[9]*c[4]+b[10]*c[8]+b[11]*c[12];d[9]=b[8]*c[1]+b[9]*c[5]+b[10]*c[9]+b[11]*c[13];d[10]=b[8]*c[2]+b[9]*c[6]+b[10]*c[10]+b[11]*c[14];d[11]=b[8]*c[3]+b[9]*c[7]+b[10]*
c[11]+b[11]*c[15];d[12]=b[12]*c[0]+b[13]*c[4]+b[14]*c[8]+b[15]*c[12];d[13]=b[12]*c[1]+b[13]*c[5]+b[14]*c[9]+b[15]*c[13];d[14]=b[12]*c[2]+b[13]*c[6]+b[14]*c[10]+b[15]*c[14];d[15]=b[12]*c[3]+b[13]*c[7]+b[14]*c[11]+b[15]*c[15];return a};l.identity=function(b){b=b||new l;var c=b.m;c[0]=c[5]=c[10]=c[15]=1;c[1]=c[2]=c[3]=c[4]=c[6]=c[7]=c[8]=c[9]=c[11]=c[12]=c[13]=c[14]=0;return b};l.perspective=function(b,c,a,d,f){b=Math.tan(b*Math.PI/360)*a;c=b*c;return l.frustum(-c,c,-b,b,a,d,f)};l.frustum=function(b,
c,a,d,f,i,g){g=g||new l;var h=g.m;h[0]=2*f/(c-b);h[1]=0;h[2]=(c+b)/(c-b);h[3]=0;h[4]=0;h[5]=2*f/(d-a);h[6]=(d+a)/(d-a);h[7]=0;h[8]=0;h[9]=0;h[10]=-(i+f)/(i-f);h[11]=-2*i*f/(i-f);h[12]=0;h[13]=0;h[14]=-1;h[15]=0;return g};l.ortho=function(b,c,a,d,f,i,g){g=g||new l;var h=g.m;h[0]=2/(c-b);h[1]=0;h[2]=0;h[3]=-(c+b)/(c-b);h[4]=0;h[5]=2/(d-a);h[6]=0;h[7]=-(d+a)/(d-a);h[8]=0;h[9]=0;h[10]=-2/(i-f);h[11]=-(i+f)/(i-f);h[12]=0;h[13]=0;h[14]=0;h[15]=1;return g};l.scale=function(b,c,a,d){d=d||new l;var f=d.m;
f[0]=b;f[1]=0;f[2]=0;f[3]=0;f[4]=0;f[5]=c;f[6]=0;f[7]=0;f[8]=0;f[9]=0;f[10]=a;f[11]=0;f[12]=0;f[13]=0;f[14]=0;f[15]=1;return d};l.translate=function(b,c,a,d){d=d||new l;var f=d.m;f[0]=1;f[1]=0;f[2]=0;f[3]=b;f[4]=0;f[5]=1;f[6]=0;f[7]=c;f[8]=0;f[9]=0;f[10]=1;f[11]=a;f[12]=0;f[13]=0;f[14]=0;f[15]=1;return d};l.rotate=function(b,c,a,d,f){if(!b||!c&&!a&&!d)return l.identity(f);f=f||new l;var i=f.m,g=Math.sqrt(c*c+a*a+d*d);b*=Math.PI/180;c/=g;a/=g;d/=g;g=Math.cos(b);b=Math.sin(b);var h=1-g;i[0]=c*c*h+g;
i[1]=c*a*h-d*b;i[2]=c*d*h+a*b;i[3]=0;i[4]=a*c*h+d*b;i[5]=a*a*h+g;i[6]=a*d*h-c*b;i[7]=0;i[8]=d*c*h-a*b;i[9]=d*a*h+c*b;i[10]=d*d*h+g;i[11]=0;i[12]=0;i[13]=0;i[14]=0;i[15]=1;return f};l.lookAt=function(b,c,a,d,f,i,g,h,k,m){m=m||new l;var n=m.m;b=new j(b,c,a);d=new j(d,f,i);h=new j(g,h,k);g=b.subtract(d).unit();h=h.cross(g).unit();k=g.cross(h).unit();n[0]=h.x;n[1]=h.y;n[2]=h.z;n[3]=-h.dot(b);n[4]=k.x;n[5]=k.y;n[6]=k.z;n[7]=-k.dot(b);n[8]=g.x;n[9]=g.y;n[10]=g.z;n[11]=-g.dot(b);n[12]=0;n[13]=0;n[14]=0;
n[15]=1;return m};w.prototype={add:function(b){var c=JSON.stringify(b);if(!(c in this.map)){this.map[c]=this.unique.length;this.unique.push(b)}return this.map[c]}};x.prototype={compile:function(b){for(var c=[],a=0;a<this.data.length;a+=1E4)c=Array.prototype.concat.apply(c,this.data.slice(a,a+1E4));a=this.data.length?c.length/this.data.length:0;if(a!=Math.round(a))throw"buffer elements not of consistent size, average size is "+a;this.buffer=this.buffer||e.createBuffer();this.buffer.length=c.length;
this.buffer.spacing=a;e.bindBuffer(this.target,this.buffer);e.bufferData(this.target,new this.type(c),b||e.STATIC_DRAW)}};p.prototype={addVertexBuffer:function(b,c){(this.vertexBuffers[c]=new x(e.ARRAY_BUFFER,Float32Array)).name=b;this[b]=[]},addIndexBuffer:function(b){this.indexBuffers[b]=new x(e.ELEMENT_ARRAY_BUFFER,Int16Array);this[b]=[]},compile:function(){for(var b in this.vertexBuffers){var c=this.vertexBuffers[b];c.data=this[c.name];c.compile()}for(var a in this.indexBuffers){c=this.indexBuffers[a];
c.data=this[a];c.compile()}},transform:function(b){this.vertices=this.vertices.map(function(a){return b.transformPoint(j.fromArray(a)).toArray()});if(this.normals){var c=b.inverse().transpose();this.normals=this.normals.map(function(a){return c.transformVector(j.fromArray(a)).unit().toArray()})}this.compile();return this},computeNormals:function(){this.normals||this.addVertexBuffer("normals","gl_Normal");for(var b=0;b<this.vertices.length;b++)this.normals[b]=new j;for(b=0;b<this.triangles.length;b++){var c=
this.triangles[b],a=j.fromArray(this.vertices[c[0]]),d=j.fromArray(this.vertices[c[1]]),f=j.fromArray(this.vertices[c[2]]);a=d.subtract(a).cross(f.subtract(a)).unit();this.normals[c[0]]=this.normals[c[0]].add(a);this.normals[c[1]]=this.normals[c[1]].add(a);this.normals[c[2]]=this.normals[c[2]].add(a)}for(b=0;b<this.vertices.length;b++)this.normals[b]=this.normals[b].unit().toArray();this.compile();return this},computeWireframe:function(){for(var b=new w,c=0;c<this.triangles.length;c++)for(var a=this.triangles[c],
d=0;d<a.length;d++){var f=a[d],i=a[(d+1)%a.length];b.add([Math.min(f,i),Math.max(f,i)])}this.lines||this.addIndexBuffer("lines");this.lines=b.unique;this.compile();return this},getAABB:function(){var b={min:new j(Number.MAX_VALUE,Number.MAX_VALUE,Number.MAX_VALUE)};b.max=b.min.negative();for(var c=0;c<this.vertices.length;c++){var a=j.fromArray(this.vertices[c]);b.min=j.min(b.min,a);b.max=j.max(b.max,a)}return b},getBoundingSphere:function(){var b=this.getAABB();b={center:b.min.add(b.max).divide(2),
radius:0};for(var c=0;c<this.vertices.length;c++)b.radius=Math.max(b.radius,j.fromArray(this.vertices[c]).subtract(b.center).length());return b}};p.plane=function(b){b=b||{};var c=new p(b);detailX=b.detailX||b.detail||1;detailY=b.detailY||b.detail||1;for(b=0;b<=detailY;b++)for(var a=b/detailY,d=0;d<=detailX;d++){var f=d/detailX;c.vertices.push([2*f-1,2*a-1,0]);c.coords&&c.coords.push([f,a]);c.normals&&c.normals.push([0,0,1]);if(d<detailX&&b<detailY){f=d+b*(detailX+1);c.triangles.push([f,f+1,f+detailX+
1]);c.triangles.push([f+detailX+1,f+1,f+detailX+2])}}c.compile();return c};var F=[[0,4,2,6,-1,0,0],[1,3,5,7,+1,0,0],[0,1,4,5,0,-1,0],[2,6,3,7,0,+1,0],[0,2,1,3,0,0,-1],[4,5,6,7,0,0,+1]];p.cube=function(b){b=new p(b);for(var c=0;c<F.length;c++){for(var a=F[c],d=c*4,f=0;f<4;f++){b.vertices.push(E(a[f]).toArray());b.coords&&b.coords.push([f&1,(f&2)/2]);b.normals&&b.normals.push(a.slice(4,7))}b.triangles.push([d,d+1,d+2]);b.triangles.push([d+2,d+1,d+3])}b.compile();return b};p.sphere=function(b){b=b||
{};var c=new p(b),a=new w;detail=b.detail||6;for(b=0;b<8;b++)for(var d=E(b),f=d.x*d.y*d.z>0,i=[],g=0;g<=detail;g++){for(var h=0;g+h<=detail;h++){var k=g/detail,m=h/detail,n=(detail-g-h)/detail;m={vertex:(new j(k+(k-k*k)/2,m+(m-m*m)/2,n+(n-n*n)/2)).unit().multiply(d).toArray()};if(c.coords)m.coord=d.y>0?[1-k,n]:[n,1-k];i.push(a.add(m))}if(g>0)for(h=0;g+h<=detail;h++){k=(g-1)*(detail+1)+(g-1-(g-1)*(g-1))/2+h;m=g*(detail+1)+(g-g*g)/2+h;c.triangles.push(f?[i[k],i[m],i[k+1]]:[i[k],i[k+1],i[m]]);g+h<detail&&
c.triangles.push(f?[i[m],i[m+1],i[k+1]]:[i[m],i[k+1],i[m+1]])}}c.vertices=a.unique.map(function(o){return o.vertex});if(c.coords)c.coords=a.unique.map(function(o){return o.coord});if(c.normals)c.normals=c.vertices;c.compile();return c};p.load=function(b,c){c=c||{};if(!("coords"in c))c.coords=!!b.coords;if(!("normals"in c))c.normals=!!b.normals;if(!("triangles"in c))c.triangles=!!b.triangles;if(!("lines"in c))c.lines=!!b.lines;var a=new p(c);a.vertices=b.vertices;if(a.coords)a.coords=b.coords;if(a.normals)a.normals=
b.normals;if(a.triangles)a.triangles=b.triangles;if(a.lines)a.lines=b.lines;a.compile();return a};t.prototype={mergeWith:function(b){if(b.t>0&&b.t<this.t){this.t=b.t;this.hit=b.hit;this.normal=b.normal}}};u.prototype={getRayForPixel:function(b,c){b=(b-this.viewport[0])/this.viewport[2];c=1-(c-this.viewport[1])/this.viewport[3];var a=j.lerp(this.ray00,this.ray10,b),d=j.lerp(this.ray01,this.ray11,b);return j.lerp(a,d,c).unit()}};u.hitTestBox=function(b,c,a,d){var f=a.subtract(b).divide(c),i=d.subtract(b).divide(c),
g=j.min(f,i);f=j.max(f,i);g=g.max();f=f.min();if(g>0&&g<f){b=b.add(c.multiply(g));a=a.add(1.0E-6);d=d.subtract(1.0E-6);return new t(g,b,new j((b.x>d.x)-(b.x<a.x),(b.y>d.y)-(b.y<a.y),(b.z>d.z)-(b.z<a.z)))}return null};u.hitTestSphere=function(b,c,a,d){var f=b.subtract(a),i=c.dot(c),g=2*c.dot(f);f=f.dot(f)-d*d;f=g*g-4*i*f;if(f>0){i=(-g-Math.sqrt(f))/(2*i);b=b.add(c.multiply(i));return new t(i,b,b.subtract(a).divide(d))}return null};u.hitTestTriangle=function(b,c,a,d,f){var i=d.subtract(a),g=f.subtract(a);
f=i.cross(g).unit();d=f.dot(a.subtract(b)).divide(f.dot(c));if(d>0){b=b.add(c.multiply(d));var h=b.subtract(a);a=g.dot(g);c=g.dot(i);g=g.dot(h);var k=i.dot(i);i=i.dot(h);h=a*k-c*c;k=(k*g-c*i)/h;i=(a*i-c*g)/h;if(k>=0&&i>=0&&k+i<=1)return new t(d,b,f)}return null};var O=new l,G=new l;y.prototype={uniforms:function(b){e.useProgram(this.program);for(var c in b){var a=e.getUniformLocation(this.program,c);if(a){var d=b[c];if(d instanceof j)d=[d.x,d.y,d.z];else if(d instanceof l)d=d.m;var f=Object.prototype.toString.call(d);
if(f=="[object Array]"||f=="[object Float32Array]")switch(d.length){case 1:e.uniform1fv(a,new Float32Array(d));break;case 2:e.uniform2fv(a,new Float32Array(d));break;case 3:e.uniform3fv(a,new Float32Array(d));break;case 4:e.uniform4fv(a,new Float32Array(d));break;case 9:e.uniformMatrix3fv(a,false,new Float32Array([d[0],d[3],d[6],d[1],d[4],d[7],d[2],d[5],d[8]]));break;case 16:e.uniformMatrix4fv(a,false,new Float32Array([d[0],d[4],d[8],d[12],d[1],d[5],d[9],d[13],d[2],d[6],d[10],d[14],d[3],d[7],d[11],
d[15]]));break;default:throw"don't know how to load uniform \""+c+'" of length '+d.length;}else{f=Object.prototype.toString.call(d);if(f=="[object Number]"||f=="[object Boolean]")(this.isSampler[c]?e.uniform1i:e.uniform1f).call(e,a,d);else throw'attempted to set uniform "'+c+'" to invalid value '+d;}}}return this},draw:function(b,c){this.drawBuffers(b.vertexBuffers,b.indexBuffers[c==e.LINES?"lines":"triangles"],arguments.length<2?e.TRIANGLES:c)},drawBuffers:function(b,c,a){this.uniforms({_gl_ModelViewMatrix:e.modelviewMatrix,
_gl_ProjectionMatrix:e.projectionMatrix});this.needsMVPM&&this.uniforms({_gl_ModelViewProjectionMatrix:l.multiply(e.projectionMatrix,e.modelviewMatrix,G)});if(this.needsNM){var d=l.transpose(l.inverse(e.modelviewMatrix,O),G).m;this.uniforms({_gl_NormalMatrix:[d[0],d[1],d[2],d[4],d[5],d[6],d[8],d[9],d[10]]})}d=0;for(var f in b){var i=b[f],g=this.attributes[f]||e.getAttribLocation(this.program,f.replace(/^gl_/,"_gl_"));if(!(g==-1||!i.buffer)){this.attributes[f]=g;e.bindBuffer(e.ARRAY_BUFFER,i.buffer);
e.enableVertexAttribArray(g);e.vertexAttribPointer(g,i.buffer.spacing,e.FLOAT,false,0,0);d=i.buffer.length/i.buffer.spacing}}for(f in this.attributes)f in b||e.disableVertexAttribArray(this.attributes[f]);if(d&&(!c||c.buffer))if(c){e.bindBuffer(e.ELEMENT_ARRAY_BUFFER,c.buffer);e.drawElements(a,c.buffer.length,e.UNSIGNED_SHORT,0)}else e.drawArrays(a,0,d);return this}};var z,q,A;r.prototype={bind:function(b){e.activeTexture(e.TEXTURE0+(b||0));e.bindTexture(e.TEXTURE_2D,this.id)},unbind:function(b){e.activeTexture(e.TEXTURE0+
(b||0));e.bindTexture(e.TEXTURE_2D,null)},drawTo:function(b){var c=e.getParameter(e.VIEWPORT);z=z||e.createFramebuffer();q=q||e.createRenderbuffer();e.bindFramebuffer(e.FRAMEBUFFER,z);e.bindRenderbuffer(e.RENDERBUFFER,q);if(this.width!=q.width||this.height!=q.height){q.width=this.width;q.height=this.height;e.renderbufferStorage(e.RENDERBUFFER,e.DEPTH_COMPONENT16,this.width,this.height)}e.framebufferTexture2D(e.FRAMEBUFFER,e.COLOR_ATTACHMENT0,e.TEXTURE_2D,this.id,0);e.framebufferRenderbuffer(e.FRAMEBUFFER,
e.DEPTH_ATTACHMENT,e.RENDERBUFFER,q);e.viewport(0,0,this.width,this.height);b();e.bindFramebuffer(e.FRAMEBUFFER,null);e.bindRenderbuffer(e.RENDERBUFFER,null);e.viewport(c[0],c[1],c[2],c[3])},swapWith:function(b){var c;c=b.id;b.id=this.id;this.id=c;c=b.width;b.width=this.width;this.width=c;c=b.height;b.height=this.height;this.height=c}};r.fromImage=function(b,c){c=c||{};var a=new r(b.width,b.height,c);try{e.texImage2D(e.TEXTURE_2D,0,a.format,a.format,a.type,b)}catch(d){if(location.protocol=="file:")throw'image not loaded for security reasons (serve this page over "http://" instead)';
else throw"image not loaded for security reasons (image must originate from the same domain as this page or use Cross-Origin Resource Sharing)";}c.minFilter&&c.minFilter!=e.NEAREST&&c.minFilter!=e.LINEAR&&e.generateMipmap(e.TEXTURE_2D);return a};r.fromURL=function(b,c){A=A||function(){var f=document.createElement("canvas").getContext("2d");f.canvas.width=f.canvas.height=128;for(var i=0;i<f.canvas.height;i+=16)for(var g=0;g<f.canvas.width;g+=16){f.fillStyle=(g^i)&16?"#FFF":"#DDD";f.fillRect(g,i,16,
16)}return f.canvas}();var a=r.fromImage(A,c),d=new Image;d.onload=function(){r.fromImage(d,c).swapWith(a)};d.src=b;return a};j.prototype={negative:function(){return new j(-this.x,-this.y,-this.z)},add:function(b){return b instanceof j?new j(this.x+b.x,this.y+b.y,this.z+b.z):new j(this.x+b,this.y+b,this.z+b)},subtract:function(b){return b instanceof j?new j(this.x-b.x,this.y-b.y,this.z-b.z):new j(this.x-b,this.y-b,this.z-b)},multiply:function(b){return b instanceof j?new j(this.x*b.x,this.y*b.y,this.z*
b.z):new j(this.x*b,this.y*b,this.z*b)},divide:function(b){return b instanceof j?new j(this.x/b.x,this.y/b.y,this.z/b.z):new j(this.x/b,this.y/b,this.z/b)},equals:function(b){return this.x==b.x&&this.y==b.y&&this.z==b.z},dot:function(b){return this.x*b.x+this.y*b.y+this.z*b.z},cross:function(b){return new j(this.y*b.z-this.z*b.y,this.z*b.x-this.x*b.z,this.x*b.y-this.y*b.x)},length:function(){return Math.sqrt(this.dot(this))},unit:function(){return this.divide(this.length())},min:function(){return Math.min(Math.min(this.x,
this.y),this.z)},max:function(){return Math.max(Math.max(this.x,this.y),this.z)},toAngles:function(){return{theta:Math.atan2(this.z,this.x),phi:Math.asin(this.y/this.length())}},toArray:function(b){return[this.x,this.y,this.z].slice(0,b||3)},clone:function(){return new j(this.x,this.y,this.z)},init:function(b,c,a){this.x=b;this.y=c;this.z=a;return this}};j.negative=function(b,c){c.x=-b.x;c.y=-b.y;c.z=-b.z;return c};j.add=function(b,c,a){if(c instanceof j){a.x=b.x+c.x;a.y=b.y+c.y;a.z=b.z+c.z}else{a.x=
b.x+c;a.y=b.y+c;a.z=b.z+c}return a};j.subtract=function(b,c,a){if(c instanceof j){a.x=b.x-c.x;a.y=b.y-c.y;a.z=b.z-c.z}else{a.x=b.x-c;a.y=b.y-c;a.z=b.z-c}return a};j.multiply=function(b,c,a){if(c instanceof j){a.x=b.x*c.x;a.y=b.y*c.y;a.z=b.z*c.z}else{a.x=b.x*c;a.y=b.y*c;a.z=b.z*c}return a};j.divide=function(b,c,a){if(c instanceof j){a.x=b.x/c.x;a.y=b.y/c.y;a.z=b.z/c.z}else{a.x=b.x/c;a.y=b.y/c;a.z=b.z/c}return a};j.cross=function(b,c,a){a.x=b.y*c.z-b.z*c.y;a.y=b.z*c.x-b.x*c.z;a.z=b.x*c.y-b.y*c.x;return a};
j.unit=function(b,c){var a=b.length();c.x=b.x/a;c.y=b.y/a;c.z=b.z/a;return c};j.fromAngles=function(b,c){return new j(Math.cos(b)*Math.cos(c),Math.sin(c),Math.sin(b)*Math.cos(c))};j.randomDirection=function(){return j.fromAngles(Math.random()*Math.PI*2,Math.asin(Math.random()*2-1))};j.min=function(b,c){return new j(Math.min(b.x,c.x),Math.min(b.y,c.y),Math.min(b.z,c.z))};j.max=function(b,c){return new j(Math.max(b.x,c.x),Math.max(b.y,c.y),Math.max(b.z,c.z))};j.lerp=function(b,c,a){return c.subtract(b).multiply(a).add(b)};
j.fromArray=function(b){return new j(b[0],b[1],b[2])};return v}();
